### ISSUE TITLE
Problem with syntax hightlighting

### ISSUE THREAD

**Issue by Philippe-Collignon** [technosophos/vscode-helm#16]
If two directives are separated by a dash or any other symbol, the second one is in another color:

Environment:
Latest version of vscode on linux :  (code_1.35.0-1559611369_amd64.deb)
Latest version of helm vscode extension :  (vscode-helm 0.4.0, kubernetes ext 1.0.0, yaml ext: 0.4.1)

How to reproduce : 
Try this snippet, `{{ .Release.Name }}` is in black  `-{{ .Chart.Name }}` is in blue (with my vscode light theme)
``` 
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}  
```
